# Generated by Django 5.1.15 on 2026-10-01 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, verbose_name='管理者ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=128, verbose_name='パスワード')),
                ('role', models.IntegerField(choices=[(0, '管理者'), (1, '共同研究者')], verbose_name='管理者区分')),
            ],
            options={
                'verbose_name': '管理者情報',
                'db_table': 'admin_info',
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False, verbose_name='端末ID')),
                ('name', models.CharField(max_length=100, verbose_name='端末名')),
                ('cpu_usage', models.FloatField(verbose_name='CPU使用率(%)')),
                ('storage_usage', models.FloatField(verbose_name='ストレージ使用率(%)')),
                ('network_status', models.IntegerField(choices=[(0, '接続'), (1, '切断')], verbose_name='ネットワーク状態')),
                ('checked_at', models.DateTimeField(verbose_name='確認日時')),
            ],
            options={
                'verbose_name': '端末情報',
                'db_table': 'device_info',
            },
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False, verbose_name='場所ID')),
                ('name', models.CharField(max_length=100, verbose_name='場所名')),
                ('capacity', models.IntegerField(verbose_name='最大定員')),
            ],
            options={
                'verbose_name': '場所マスター',
                'db_table': 'location_master',
            },
        ),
        migrations.CreateModel(
            name='DayOfWeekSummaryLog',
            fields=[
                ('dow_log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='曜日集計ID')),
                ('summary_month', models.DateTimeField(verbose_name='集計対象月')),
                ('day_of_week', models.IntegerField(choices=[(0, '日曜日'), (1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日')], verbose_name='曜日')),
                ('avg_count', models.FloatField(verbose_name='平均利用者数')),
                ('executed_at', models.DateTimeField(verbose_name='集計実行日時')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='crowd_app.locationmaster', verbose_name='場所ID')),
            ],
            options={
                'verbose_name': '曜日別集計ログ',
                'db_table': 'day_of_week_summary_log',
            },
        ),
        migrations.CreateModel(
            name='CrowdPrediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False, verbose_name='予測ID')),
                ('expected_count', models.IntegerField(verbose_name='予測利用者数')),
                ('predicted_at', models.DateTimeField(verbose_name='予測日時')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='crowd_app.locationmaster', verbose_name='場所ID')),
            ],
            options={
                'verbose_name': '混雑予測情報',
                'db_table': 'crowd_prediction',
            },
        ),
        migrations.CreateModel(
            name='CrowdLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='記録ID')),
                ('user_count', models.IntegerField(verbose_name='利用者数')),
                ('crowd_rate', models.FloatField(verbose_name='混雑率(%)')),
                ('recorded_at', models.DateTimeField(verbose_name='記録日時')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='crowd_app.locationmaster', verbose_name='場所ID')),
            ],
            options={
                'verbose_name': '混雑状況記録',
                'db_table': 'crowd_log',
            },
        ),
        migrations.CreateModel(
            name='CameraInfo',
            fields=[
                ('camera_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='カメラID')),
                ('name', models.CharField(max_length=100, verbose_name='カメラ名')),
                ('camera_type', models.IntegerField(choices=[(0, 'Raspberry Pi Camera'), (1, 'USB Webcam'), (2, 'IP Camera / RTSP'), (3, 'Video File (Test)')], verbose_name='カメラ種類')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '異常'), (2, '不通')], verbose_name='稼働状態')),
                ('installed_at', models.DateTimeField(verbose_name='設置日時')),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='crowd_app.deviceinfo', verbose_name='端末ID')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='crowd_app.locationmaster', verbose_name='場所ID')),
            ],
            options={
                'verbose_name': 'カメラ情報',
                'db_table': 'camera_info',
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False, verbose_name='レポートID')),
                ('summary_month', models.DateTimeField(verbose_name='集計対象月')),
                ('avg_utilization', models.FloatField(verbose_name='平均利用率(%)')),
                ('max_users', models.IntegerField(verbose_name='最大利用者数')),
                ('total_creations', models.IntegerField(default=1, verbose_name='総作成回数')),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='crowd_app.admininfo', verbose_name='管理者ID')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='crowd_app.locationmaster', verbose_name='場所ID')),
            ],
            options={
                'verbose_name': '月次レポート',
                'db_table': 'monthly_report',
            },
        ),
        migrations.CreateModel(
            name='WeeklySummaryLog',
            fields=[
                ('weekly_log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='週間集計ID')),
                ('start_at', models.DateTimeField(verbose_name='集計開始日時')),
                ('end_at', models.DateTimeField(verbose_name='集計終了日時')),
                ('avg_count', models.FloatField(verbose_name='平均利用者数')),
                ('max_count', models.IntegerField(verbose_name='最大利用者数')),
                ('executed_at', models.DateTimeField(verbose_name='集計実行日時')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='crowd_app.locationmaster', verbose_name='場所ID')),
            ],
            options={
                'verbose_name': '週間集計ログ',
                'db_table': 'weekly_summary_log',
            },
        ),
    ]
