# Generated by Django 5.1.15 on 2026-10-02 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdlog',
            name='user_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='利用者人数は0以上で入力してください。')], verbose_name='利用者数'),
        ),
        migrations.AddConstraint(
            model_name='crowdlog',
            constraint=models.CheckConstraint(condition=models.Q(('user_count__gte', 0)), name='crowd_log_user_count_nonnegative'),
        ),
    ]
