# Generated by Django 5.1.15 on 2026-10-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_app', '0002_alter_crowdlog_user_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdlog',
            name='crowd_rate',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='混雑率(%)'),
        ),
    ]
